### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by SweeWarman** [nasa/daa-displays#16]
I get the following compile error when trying to compile the current version on master ([0a7737d](https://github.com/nasa/daa-displays/commit/0a7737d40971488cf024ea6b984dcdbc89505c91)). I am able to compile the [previous commit](https://github.com/nasa/daa-displays/commit/c890f4f4d7ab901044ef5c5098ce01841a451db6) without issues.

DAA2PVS.java:48: error: package gov.nasa.larcfm.ACCoRD does not exist
import gov.nasa.larcfm.ACCoRD.BandsRegion;
                             ^
DAA2PVS.java:49: error: package gov.nasa.larcfm.ACCoRD does not exist
import gov.nasa.larcfm.ACCoRD.Daidalus;
                             ^
DAA2PVS.java:50: error: package gov.nasa.larcfm.ACCoRD does not exist
import gov.nasa.larcfm.ACCoRD.DaidalusFileWalker;
                             ^
DAA2PVS.java:51: error: package gov.nasa.larcfm.ACCoRD does not exist
import gov.nasa.larcfm.ACCoRD.KinematicBandsParameters;
                             ^
DAA2PVS.java:52: error: package gov.nasa.larcfm.ACCoRD does not exist
import gov.nasa.larcfm.ACCoRD.KinematicMultiBands;
                             ^
DAA2PVS.java:53: error: package gov.nasa.larcfm.Util does not exist
import gov.nasa.larcfm.Util.Units;
                           ^
DAA2PVS.java:54: error: package gov.nasa.larcfm.Util does not exist
import gov.nasa.larcfm.Util.Util;
                           ^
DAA2PVS.java:55: error: package gov.nasa.larcfm.Util does not exist
import gov.nasa.larcfm.Util.f;
                           ^
DAA2PVS.java:61: error: cannot find symbol
    Daidalus daa = null;
    ^
  symbol:   class Daidalus
  location: class DAA2PVS
DAA2PVS.java:72: error: cannot find symbol
	daa = new Daidalus();
	          ^
  symbol:   class Daidalus
  location: class DAA2PVS
DAA2PVS.java:76: error: cannot find symbol
	return KinematicBandsParameters.VERSION;
	       ^
  symbol:   variable KinematicBandsParameters
  location: class DAA2PVS
DAA2PVS.java:189: error: cannot find symbol
	DaidalusFileWalker walker = new DaidalusFileWalker(ifname);
	^
  symbol:   class DaidalusFileWalker
  location: class DAA2PVS
DAA2PVS.java:189: error: cannot find symbol
	DaidalusFileWalker walker = new DaidalusFileWalker(ifname);
	                                ^
  symbol:   class DaidalusFileWalker
  location: class DAA2PVS
13 errors
make[2]: *** [Makefile:78: codev1-DAA2PVS] Error 1
make[2]: Leaving directory '/home/swee/Projects/daa-displays/dist/daa-logic'
make[1]: *** [Makefile:14: compile] Error 2
make[1]: Leaving directory '/home/swee/Projects/daa-displays/dist'
make: *** [Makefile:66: compile] Error 2

**Comment by cesaramh** [comment]
Fixed. The issue is that the Makefile requires at least one v1.0 in the compilation chain. The fix is to uncomment v.1.2 from dist/releases.

**Comment by emanuelazfernandes** [comment]
The issue is still happening, I was only able to compile v2.0.3: 906f73da77793a722331cea5c6e32b2d4efc344a

**Comment by cesaramh** [comment]
Check that v1.0.2 is uncommented in daidalus-modules/releases.
